#include <ruby.h>
#include <pcg_variants.h>
#include <stdbool.h>

#include "entropy.h"
#include "rb_constants.h"
#include "pcg_seed.h"

/* Functions local to this source file */
static VALUE pcg_new_seed_bytestr(void);
static VALUE pcg_raw_seed_bytestr(size_t size);
static VALUE pcg_rb_unpack_str_ui64(VALUE str);

/*
 * Returns a 128-bit big-integer that stores the seed value used to seed the 
 * initial state and sequence for the PCG generator.
 */ 
VALUE
pcg_func_new_seed(void)
{
    return pcg_new_seed_bytestr();
}

/*
 * Generates a random seed represented as a sequence of bytes 
 */
VALUE
pcg_func_raw_seed(VALUE self, VALUE byte_size)
{
    unsigned long n = NUM2ULONG(byte_size);
    if( n == 0 )
    {
        return rb_str_new2("\0");
    }
    return pcg_raw_seed_bytestr(n);
}

/*
 * Generates a sequence of random bytes using device entropy
 * or a fallback mechanism based on pcg32_random_r
 */
bool 
pcg_func_entropy_getbytes(void *dest, size_t size)
{
    /* Get random bytes from /dev/random or a fallback source */
    if( !entropy_getbytes(dest, size) )
    {
        fallback_entropy_getbytes(dest, size);
        return true;
    }
    return false;
}

/*
 * Internal - Unpacks a string `str` wuth str.unpack('Q*')
 * Unpacks and returns the 0th entry (since it's always a 1 element array)
 */
static VALUE
pcg_rb_unpack_str_ui64(VALUE str)
{
    VALUE ary = rb_funcall(str, rb_intern("unpack"), 1, rb_str_new2("Q*\0"));
    return rb_ary_entry(ary, 0);
}

/*
 * Internal - gets `size` number of random bytes from a platform source
 * and returns those as a ruby string
 */
static VALUE
pcg_raw_seed_bytestr(size_t size)
{
    char *bytestr = (char *) malloc(size + 1);
    memset(bytestr, 0, size + 1);
    pcg_func_entropy_getbytes((void *)bytestr, size);
    
    return rb_str_new2(bytestr);
}

/*
 * Internal - Two random integers are sourced from /dev/random or a fallback
 * technique. 
 * Seed generated by manipulating a 16byte string & unpacking it to Q*
 * 
 * @see pcg_new_seed_bigmul() for alternative techniques
 */
static VALUE
pcg_new_seed_bytestr(void)
{
    VALUE seed_bytes_str;
    
    seed_bytes_str = pcg_raw_seed_bytestr(2 * sizeof(uint64_t));
    return pcg_rb_unpack_str_ui64(seed_bytes_str);
}

